services:
  dev:
    depends_on: [firebase]
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
      target: base
    command: npm run dev -- --host
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  test:
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
      target: test
    command: npm run test
    tty: true
  test-watch:
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
      target: base
    command: npm run test:watch
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    tty: true
  firebase:
    container_name: firebase
    image: andreysenov/firebase-tools
    user: node
    command: firebase emulators:start --config docker-firebase.json
    ports:
      - 4000:4000
      - 4400:4400
      - 4500:4500
      - 8080:8080
      - 8085:8085
      - 9000:9000
      - 9005:9005
      - 9099:9099
      - 9150:9150
      - 9199:9199
    volumes:
      - .:/home/node
  app:
    image: '${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${STAGE}/${IMAGE_NAME}:${VERSION}'
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: prod
    command: node build
    ports:
      - 3000:3000
volumes:
  node_modules:
