services:
  dev:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: base
    command: npm run dev -- --host
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules
  test:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: test
    command: npm run test
    tty: true
  test-watch:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: base
    command: npm run test:watch
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
  app:
    image: 'ghcr.io/huhwhuh/ashfish:${TAG}'
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: prod
    command: node build
    ports:
      - 3000:3000
