services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: base
    command: npm run dev -- --host
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
  test-integration:
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    command: npm run test:integration
    tty: true
  test-unit:
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    command: npm run test:unit
    tty: true
  test:
    build:
      context: .
      dockerfile: ./docker/test/Dockerfile
    command: npm run test
    tty: true

