name: CI/CD
on:
  pull_request:
  push: { branches: [master] }
jobs:
  lint:
    name: Check Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verify package-lock.json is up to date
        run: npx --yes package-lock-utd@1.x.x

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
  test:
    name: Run Testing Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Images
        run: docker compose build test

      - name: Run Unit Tests
        run: docker compose run test npm run test:unit

      - name: Run Integration Tests
        run: docker compose run test npm run test:integration

  deployment:
    needs: [test, lint]
    name: Deploy to remote server (not implemented)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
