name: Test PR
on:
  pull_request:
    branches:
      - develop
jobs:
  lint:
    name: Check Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
  tests:
    name: Run Testing Suite
    needs: lint
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Run Integration Tests
        run: npm run test:integ
