name: Test PR
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  lint:
    name: Check Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
  tests:
    name: Run Testing Suite
    needs: lint
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/bake-action@v4
        with:
          targets: test
          load: true

      - name: Run Unit Tests
        run: docker compose run --rm test npm run test:unit

      - name: Run Integration Tests
        run: docker compose run --rm test npm run test:integ
